import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar";

// ─── Translation Dictionary ───────────────────────────────────────────────────
export const translations = {
  en: {
    // Navigation
    nav_home: "Home",
    nav_restaurants: "Restaurants",
    nav_schedule: "Schedule",
    nav_affiliate: "Affiliate",
    nav_profile: "Profile",
    // BMI labels
    normal: "Normal",
    overweight: "Overweight",
    obese: "Obese",
    underweight: "Underweight",
    // Tracker
    starting: "Starting",
    // Profile
    save_changes: "Save Changes",
    profile_settings: "Profile & Settings",
    profile_details: "Profile Details",
    update_your_profile_details: "Update your profile details",
    loading_profile: "Loading profile...",
    free_plan: "Free Plan",
    joined: "Joined",
    email_address: "Email Address",
    personal_info_desc: "Name, gender, age and email address",
    full_name_label: "Full Name",
    enter_full_name: "Enter your full name",
    enter_new_password: "Enter new password",
    confirm_new_password: "Confirm new password",
    apply_affiliate_program: "Apply for Affiliate Program",
    when_restaurants_add_items: "When restaurants add new items",
    tailor_meals_offers: "Tailor meals and offers to your habits",
    help_improve_app: "Help us improve the app with anonymous data",
    notification_settings: "Notification Settings",
    // Profile page
    order_updates: "Order Updates",
    status_changes_orders: "Status changes for your active orders",
    discounts_special_deals: "Discounts and special deals",
    choose_notifications: "Choose what you want to be notified about",
    control_data_usage: "Control how your data is used",
    manage_account_status: "Manage your account status",
    manage_addresses: "Manage your saved delivery locations",
    delete_account_warning: "This action cannot be undone. All your data including meal schedules, progress logs, and preferences will be permanently deleted.",
    // Dashboard
    on_fire_message: "You're on fire! Keep logging your meals.",
    days_to_milestone: "days to next milestone",
    days_this_week: "days this week",
    weekly_goal: "Weekly Goal",
    no_featured_restaurants: "No featured restaurants yet",
    check_back_restaurants: "Check back soon for our highlighted partner restaurants!",
    // Auth & Progress
    on_track_nutrition: "On track with your nutrition plan",
    eat_smart: "Eat Smart,",
    live_better: "Live Better",



    // Common
    save: "Save",
    cancel: "Cancel",
    pay_with_amount: "Pay",
    close: "Close",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "Loading...",
    saving: "Saving…",
    search: "Search",
    filter: "Filter",
    all: "All",
    yes: "Yes",
    no: "No",
    back: "Back",
    next: "Next",
    done: "Done",
    submit: "Submit",
    update: "Update",
    add: "Add",
    remove: "Remove",
    view: "View",
    share: "Share",
    download: "Download",
    upload: "Upload",
    select: "Select",
    change: "Change",
    apply: "Apply",
    reset: "Reset",
    clear: "Clear",
    ok: "OK",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    retry: "Retry",
    reload: "Reload",
    processing: "Processing...",

    // Dashboard
    good_morning: "Good morning ☀️",
    good_afternoon: "Good afternoon 🌤️",
    good_evening: "Good evening 🌙",
    todays_progress: "Today's Progress",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    water: "Water",
    steps: "Steps",
    weight: "Weight",
    goal: "Goal",
    nutrition_eaten: "nutrition eaten",
    nutrition_cal: "cal",
    streak: "Streak",
    days: "days",
    day: "day",
    week: "Week",
    month: "Month",
    year: "Year",
    today: "Today",
    yesterday: "Yesterday",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    view_all: "View All",
    see_all: "See All",
    no_data: "No data available",
    sign_out: "Sign Out",
    signed_out: "Signed out",
    signed_out_desc: "You have been successfully signed out.",

    // Meals / Restaurants
    restaurants: "Restaurants",
    meals: "Meals",
    meal: "Meal",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snack",
    search_food: "Search food...",
    search_restaurants: "Search restaurants...",
    all_restaurants: "All Restaurants",
    your_favorites: "Your Favorites",
    favorite_meals: "Favorite Meals",
    no_restaurants_found: "No restaurants found",
    no_meals_found: "No meals found",
    no_favorites_yet: "No favorites yet",
    no_favorite_meals_yet: "No favorite meals yet",
    available_now: "Available now",
    currently_unavailable: "Currently unavailable",
    delicious_healthy_meals: "Delicious healthy meals",
    healthy_and_delicious: "Healthy & delicious meals",
    fastest: "Fastest",
    popular: "Popular",
    top_rated: "Top Rated",
    favorites: "Favorites",
    filters: "Filters",
    under_300: "Under 300",
    add_to_cart: "Add to Cart",
    order_now: "Order Now",
    calories_kcal: "Calories (kcal)",
    kcal: "kcal",
    g: "g",
    ml: "mL",
    cups: "cups",
    kg: "kg",
    cm: "cm",

    // Schedule
    schedule: "Schedule",
    set_delivery_time: "Set delivery time",
    delivery_time_set: "Delivery Time Set",

    // Progress / Tracker
    progress: "Progress",
    tracker: "Tracker",
    insights: "Insights",
    bmi: "BMI",
    edit_bmi: "Edit BMI",
    height: "Height",
    add_steps: "Add steps",
    step_goal: "Step Goal",
    water_intake: "Water Intake",
    weight_goal: "Weight Goal",
    calorie_goal: "Calorie Goal",
    protein_goal: "Protein Goal",
    log_meal: "Log Meal",
    log_activity: "Log Activity",
    weekly_report: "Weekly Report",
    download_report: "Download Report",
    generating_report: "Generating report...",
    report_downloaded: "Report downloaded!",
    report_failed: "Failed to generate report",
    scan_food: "Scan Food",
    take_photo: "Take Photo",
    upload_from_gallery: "Upload from Gallery",
    scan_your_food: "Scan Your Food",
    scan_desc: "Take a photo or upload from your gallery to identify the food and log it instantly.",
    recent: "Recent",
    manual_log: "Manual Log",
    select_items_to_add: "Select items to add",
    use_camera_to_capture: "Use your camera to capture food",
    pick_existing_photo: "Pick an existing photo",

    // Profile / Settings
    profile: "Profile",
    settings: "Settings",
    profile_and_settings: "Profile & Settings",
    personal_info: "Personal Info",
    account_actions: "Account Actions",
    update_profile_details: "Update your profile details",
    update_profile_button: "Update Profile",
    manage_account: "Manage your account status",
    delete_account: "Delete Account",
    language: "Language",
    select_language: "Select your preferred language",
    english: "English",
    arabic: "العربية",
    notifications: "Notifications",
    privacy_settings: "Privacy Settings",
    control_data: "Control how your data is used",
    usage_analytics: "Usage Analytics",
    usage_analytics_desc: "Help us improve the app with anonymous data",
    personalised_recommendations: "Personalised Recommendations",
    personalised_desc: "Tailor meals and offers to your habits",
    new_meals_available: "New Meals Available",
    new_meals_desc: "When restaurants add new items",
    promotions_offers: "Promotions & Offers",
    promotions_desc: "Discounts and special deals",
    profile_updated: "Profile updated",
    personal_info_saved: "Your personal information has been saved.",
    password_updated: "Password updated",
    passwords_dont_match: "Passwords don't match",
    password_min_length: "Password must be at least 6 characters.",
    contact_support: "Contact support",
    view_affiliate_dashboard: "View Affiliate Dashboard",
    apply_affiliate: "Apply for Affiliate Program",
    
    // Profile related
    saving_now: "Saving...",
    profile_updated_success: "Profile updated",
    personal_info_saved_success: "Your personal information has been saved.",
    error_saving_profile: "Error saving profile",
    failed_load_dietary_preferences: "Failed to load dietary preferences",
    removed: "Removed",
    added: "Added",
    failed_update_dietary_preference: "Failed to update dietary preference",
    passwords_match_warning: "Please make sure your new passwords match.",
    password_changed_success: "Your password has been changed successfully.",
    error_updating_password: "Error updating password",
    contact_support_delete_account: "Please contact support to delete your account.",
    successful: "Successful",
    please_try_again: "Please try again.",
    password_too_short: "Password too short",
    password_must_be_at_least_6_characters: "Password must be at least 6 characters.",
    password_updated_description: "Your password has been changed successfully.",
    updated_successfully: "Updated successfully",
    added_successfully: "Added successfully",
    removed_successfully: "Removed successfully",
    
    // Wallet related
    available_balance: "Available Balance",
    available_for_orders: "Available for orders",
    total_spent: "Total Spent",
    total_credits: "Total Credits",
    package_label: "Package",
    top_up_amount: "Top-up Amount",
    bonus_credit: "Bonus Credit",
    total_credit: "Total Credit",
    redirected_to_sadad: "You will be redirected to Sadad to complete the payment securely.",
    credit: "Credit",
    debit: "Debit",
    refund: "Refund",
    bonus: "Bonus",
    cashback: "Cashback",
    you_get: "You get",
    credits_never_expire: "Credits never expire",
    transaction_history: "Transaction History",
    no_transactions_yet: "No transactions yet",
    top_up_wallet_start: "Top up your wallet to get started",
    secure_payment_sadad: "Secure payment via Sadad",
    commission_balance: "Your commission balance",
    recent_commissions: "Recent Commissions",
    tier: "Tier",
    available: "Available",
    total_earned: "Total Earned",

     // Profile form labels
     gender: "Gender",
     age: "Age",
      years_label: "years",
      age_label: "Age",
      age_default_placeholder: "25",
     
     // Auth
    sign_in: "Sign In",
    sign_up: "Sign Up",
    create_free_account: "Create Free Account",
    email: "Email",
    password: "Password",
    forgot_password: "Forgot Password?",
    reset_password: "Reset Password",
    can_reset_password: "You can now reset your password.",
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",

    // Goals
    weight_loss: "Weight Loss",
    muscle_gain: "Muscle Gain",
    maintenance: "Maintenance",
    general_health: "General Health",
    not_enough_data: "Not enough data yet",
    no_active_goal: "No active goal",
    set_nutrition_goal: "Set a nutrition goal first so we can analyze your progress.",
    goal_optimization: "Goal optimization based on your data",

    // Wallet / Orders
    wallet: "Wallet",
    order_history: "Order History",
    invoice_history: "Invoice History",
    checkout: "Checkout",
    total: "Total",
    subtotal: "Subtotal",
    delivery_fee: "Delivery Fee",
    discount: "Discount",
    payment: "Payment",
    place_order: "Place Order",

    // Addresses
    addresses: "Addresses",
    add_address: "Add Address",
    delivery_address: "Delivery Address",

    // Subscription
    subscription: "Subscription",
    subscribe: "Subscribe",
    current_plan: "Current Plan",
    upgrade: "Upgrade",

    // Support / About
    support: "Support",
    about: "About",
    faq: "FAQ",
    contact: "Contact",
    privacy_policy: "Privacy Policy",
    terms: "Terms & Conditions",
    policies: "Policies",

    // Notifications
    notification: "Notification",
    mark_all_read: "Mark all as read",
    no_notifications: "No notifications",

    // Water tracker
    add_water: "Add Water",
    water_goal: "Water Goal",
    glasses: "glasses",
    liters: "liters",

    // Weight tracking
    log_weight: "Log Weight",
    update_weight: "Update Weight",
    weight_updated: "Weight updated",
    weight_logged: "kg logged.",
    failed_to_update: "Failed to update",
    water_added: "Water added",

    // Step counter
    step_counter: "Step Counter",
    steps_today: "Steps Today",
    distance: "Distance",
    active_time: "Active Time",

    // Onboarding
    get_started: "Get Started",
    skip: "Skip",
    continue: "Continue",
    welcome: "Welcome",
    welcome_to_nutrio: "Welcome to Nutrio",
    fuel_your_body: "FUEL Your Body Smart",

    // Errors
    something_went_wrong: "Something went wrong",
    we_apologize: "We apologize for the inconvenience. The error has been reported and we'll fix it soon.",
    reload_page: "Reload Page",
    not_found: "Page Not Found",
    go_home: "Go Home",

    // Time zones
    timezone_qatar: "Qatar (GMT +3)",

    // Gender
    he_him: "He/Him",
    she_her: "She/Her",

    // Expected impact
    expected_impact: "Expected impact",
    hide_impact: "Hide impact",

    // Show results
    show_results: "Show",
    restaurants_label: "Restaurants",
    meals_label: "Meals",

    // Report
    overall_score: "OVERALL SCORE",
    weekly_performance: "WEEKLY PERFORMANCE",
    habit_intelligence: "& HABIT INTELLIGENCE",
    weekly_report_title: "Weekly Report",
    prepared_for: "PREPARED FOR",
    generated: "Generated",

    // Auth page
    personalized_plans: "Personalized Plans",
    calorie_macro_tracking: "Calorie & Macro Tracking",
    restaurant_integration: "Restaurant Integration",
    progress_insights: "Progress & Insights",
    welcome_feature_desc: "Get meal plans tailored to your goals, dietary preferences, and lifestyle.",
    create_account: "Create Account",
    full_name: "Full Name",
    confirm_password: "Confirm Password",
    verify_email: "Verify Your Email",
    otp_sent_to: "We sent a 6-digit code to",
    enter_otp: "Enter the 6-digit code",
    verify_code: "Verify Code",
    resend_code: "Resend Code",
    back_to_signup: "Back to Sign Up",
    send_reset_link: "Send Reset Link",
    back_to_signin: "Back to Sign In",
    sign_in_required: "Sign in required",
    sign_in_required_desc: "Please sign in or create an account to continue.",
    complete: "Complete",
    male: "Male",
    female: "Female",
    prefer_not_to_say: "Prefer not to say",

    // Onboarding
    lose_weight: "Lose Weight",
    lose_weight_desc: "Reduce body fat while maintaining muscle",
    build_muscle: "Build Muscle",
    build_muscle_desc: "Gain lean muscle mass with proper nutrition",
    maintain: "Maintain",
    maintain_desc: "Keep your current weight and improve health",
    maintenance_goal: "Maintenance",
    sedentary: "Sedentary",
    sedentary_desc: "Little or no exercise",
    lightly_active: "Lightly Active",
    lightly_active_desc: "Light exercise 1-3 days/week",
    moderately_active: "Moderately Active",
    moderately_active_desc: "Moderate exercise 3-5 days/week",
    very_active: "Very Active",
    very_active_desc: "Hard exercise 6-7 days/week",
    extra_active: "Extra Active",
    extra_active_desc: "Very hard exercise & physical job",

    // Main Menu
    food_and_meals: "Food & Meals",
    plan_weekly_meals: "Plan your weekly meals",
    browse_all_restaurants: "Browse all restaurants",
    progress_and_goals: "Progress & Goals",
    track_weight_nutrition: "Track weight, nutrition & health metrics",
    updated: "Updated",
    orders_and_subscription: "Orders & Subscription",
    view_past_orders: "View past orders",
    manage_your_plan: "Manage your plan",
    upgrade_your_plan: "Upgrade your plan",
    live_tracking: "Live Tracking",
    track_your_orders: "Track your orders",
    settings_and_account: "Settings & Account",
    personal_info_preferences: "Personal info & preferences",
    app_preferences: "App preferences",
    delivery_locations: "Delivery locations",
    earn_rewards: "Earn Rewards",
    earn_with_audience: "Earn with your audience",
    affiliate: "Affiliate",
    menu: "Menu",
    saved_restaurants: "saved restaurants",

    // MealWizard
    snacks_salad: "Snacks & Salad",
    breakfast_desc: "Start your day with energy",
    lunch_desc: "Fuel your afternoon",
    dinner_desc: "End your day right",
    snacks_desc: "Healthy extras",
    back_to_restaurants: "Back to Restaurants",
    partner_restaurant: "Partner Restaurant",

    // Progress page
    great: "Great",
    good: "Good",
    keep_going: "Keep Going",
    first_week_complete: "First Week Complete",
    logged_meals_7_days: "Logged meals for 7 days",
    protein_pro: "Protein Pro",
    hit_protein_goal_5_days: "Hit protein goal 5 days",
    hydration_hero: "Hydration Hero",
    drank_8_glasses: "Drank 8 glasses for a week",
    analyzing_21_days: "Analyzing your last 21 days…",
    log_meals_4_days: "Log meals for at least 4 days to unlock personalized suggestions.",
    set_nutrition_goal_first: "Set a nutrition goal first so we can analyze your progress.",
    high_confidence_changes: "high-confidence changes",
    high_confidence: "High confidence",
    suggestion: "Suggestion",
    exploratory: "Exploratory",
    safety_tip: "Safety tip",

    // Meals Remaining Widget
    unlimited: "Unlimited",
    running_low_meals: "Running low! Only {count} meal(s) left. Choose your next meals wisely.",
    getting_low_meals: "Getting low on meals. You have {remaining} remaining out of {total}.",

    // TrackerInsights
    smart_adjustments: "Smart Adjustments",
    suggestions_based_on: "suggestions based on",

    // LogMealDialog
    log_food: "Log Food",
    search_food_items: "Search food items...",
    quick_log: "Quick Log",
    my_meals: "My Meals",
    food_name: "Food Name",
    amount: "Amount",
    unit: "Unit",
    add_food: "Add Food",
    nutrition_info: "Nutrition Info",
    per_serving: "Per serving",
    add_to_log: "Add to Log",
    serving_size: "Serving Size",

    // Schedule page
    meal_schedule: "Meal Schedule",
    plan_your_meals: "Plan your meals for the week",
    add_meal: "Add Meal",
    no_meals_scheduled: "No meals scheduled",
    delivery_timezone: "Delivery Timezone",

    // Profile page
    he_him_pronoun: "He/Him",
    she_her_pronoun: "She/Her",
    your_name: "Your Name",
    enter_email: "Enter your email",
    nutrition_goals: "Nutrition Goals",
    daily_calories: "Daily Calories",
    daily_protein: "Daily Protein",
    daily_carbs: "Daily Carbs",
    daily_fat: "Daily Fat",

    // Auth page (missing keys)
    welcome_back: "Welcome Back",
    signin_desc: "Sign in to your Nutrio account",
    remember_me: "Remember me",
    signing_in: "Signing In...",
    join_nutrio_today: "Join Nutrio Today",
    create_account_desc: "Start your personalized nutrition journey",
    i_agree_to_nutrio: "I agree to Nutrio's",
    creating_account: "Creating Account...",
    personalized_nutrition_tagline: "Track, eat, and live smarter every day.",
    feature_personalized_plans: "Personalized Plans",
    feature_personalized_plans_desc: "Get meal plans tailored to your goals and dietary needs.",
    feature_restaurant_partners: "Partner Restaurants",
    feature_restaurant_partners_desc: "Order from a curated selection of healthy restaurants.",
    feature_track_progress: "Track Progress",
    feature_track_progress_desc: "Monitor your calories, macros, and fitness metrics daily.",
    enter_otp_code: "Verify Your Email",
    otp_sent_desc: "We sent a 6-digit code to your email address.",
    resend_code_in: "Resend code in",
    seconds: "seconds",
    verifying: "Verifying...",
    verify_otp: "Verify Code",
    forgot_password_desc: "Enter your email to receive a password reset link.",
    registered_email: "Registered Email",
    sending: "Sending...",
    send_otp_code: "Send Reset Link",

    // Profile tabs (sidebar nav)
    profile_tab: "Profile",
    rewards: "Rewards",

    // Schedule page
    sign_in_to_schedule: "Sign in to view schedule",
    sign_in_to_schedule_desc: "Please sign in to view and manage your meal schedule.",
    swipe_to_change_week: "Swipe to change week",
    schedule_delivery: "Schedule Delivery",

    // TrackerInsights charts
    calorie: "Calorie",
    calorie_kcal: "Calories (kcal)",
    calorie_intake_goal: "Calorie Goal",
    water_ml: "Water (mL)",
    water_intake_goal: "Water Intake Goal",
    weight_kg: "Weight (kg)",
    log_more_weight: "Log more weight entries to see trends",
    set_height_weight_bmi: "Set your height and weight to see BMI",
    selected: "Selected",

    // LogMealDialog
    analyzing_food: "Analyzing Food",
    ai_detecting_ingredients: "AI is detecting ingredients...",
    items_detected: "items detected",
    item_detected: "item detected",
    scan_again: "Scan Again",
    scan_food_desc: "Take a photo or upload from your gallery to identify the food and log it instantly.",
    total_weight: "Total Weight",
    todays_schedule: "Today's Schedule",
    no_recent_meals: "No recent meals",
    no_results_for: "No results for",
    try_quick_log: "Try quick log",
    recently_logged: "Recently logged",
    items: "items",
    item: "item",
    food_name_placeholder: "e.g. Grilled Chicken",
    log: "Log",
    create_food: "Create Food",

    // Profile page extensions
    dietary_preference_added: "Dietary preference added",
    dietary_preference_added_description: "has been added successfully",
    dietary_preference_removed: "Dietary preference removed",
    dietary_preference_removed_description: "has been removed successfully",
    manage_addresses_action: "Manage Addresses",
    delivery_addresses: "Delivery Addresses",
    dietary_and_allergies: "Dietary & Allergies",
    manage_dietary_preferences: "Manage dietary preferences and intolerances",
    dietary_preferences: "Dietary Preferences",
    no_dietary_tags_available: "No dietary tags available",
    allergies_and_intolerances: "Allergies & Intolerances",
    profile_updated_description: "Your personal information has been saved.",
    terms_and_conditions: "Terms and Conditions",
    privacy_policy_label: "Privacy Policy",
    get_help_report_issues: "Get help, report issues, contact us",
    chat_on_whatsapp: "Chat on WhatsApp",
    email_support: "Email Support",
    call_us: "Call Us",
    submit_a_ticket: "Submit a Ticket",
    view_faq: "View FAQ",
    support_hours: "Nutrio Fuel · Support hours: 8 AM – 10 PM (Qatar)",
    my_wallet: "My Wallet",
    top_up_manage_balance: "Top-up & manage balance",
    payment_successful: "Payment successful! Your wallet has been credited.",
    payment_failed: "Payment failed. Please try again.",
    simulation_mode: "SIMULATION MODE: All payments are simulated. No real money will be charged.",
    confirm_top_up: "Confirm Top-up",
    review_top_up_details: "Review your top-up details before proceeding to payment.",
    daily_streaks: "Daily Streaks",
    order_daily_earn_bonuses: "Order daily to earn bonus credits",
    wallet_bonuses: "Wallet Bonuses",
    get_bonus_credits: "Get bonus credits on top-ups",
    top_up_packages: "Top-up Packages",
    get_bonus_credits_desc: "Get bonus credits on top-ups",
    // Streak Rewards
    streakRewardTitle: "Streak Reward",
    rewardClaimed: "Reward Claimed",
    walletCreditApplied: "Wallet Credit Applied",
    earnedReward: "Earned Reward",
    failedToClaimReward: "Failed to claim reward",
    nextReward: "Next Reward",
    daysToUnlock: "{days} days to unlock {reward}",
    availableRewards: "Available Rewards",
    dayStreak: "day streak",
    claim: "Claim",
    noRewardsAvailable: "No rewards available",
    upcoming: "Upcoming",
    allRewardsUnlocked: "All rewards unlocked",
    // Referral Milestones
    affiliate_milestone_bonuses: "Affiliate Milestone Bonuses",
    affiliate_unlocked: "unlocked",
    affiliate_progress_to: "Progress to",
    affiliate_more_referrals: "more referrals",
    affiliate_more_referral: "more referral",
    affiliate_to_earn: "to earn",
    affiliate_bonus: "bonus",
    affiliate_total_milestone_bonuses_earned: "Total Milestone Bonuses Earned",
    affiliate_achieved: "Achieved",
    affiliate_next_goal: "Next Goal",
    referrals: "referrals",
    secure_payment_sadad_credits_never_expire: "Secure payment via Sadad • Credits never expire",
    // Processing
    earn_more: "Earn More",
    affiliate_program: "Affiliate Program",
    become_affiliate: "Become an affiliate and earn multi-tier commissions (up to 3 levels deep) from your referrals.",
    change_password: "Change Password",
    update_account_password: "Update your account password",
    new_password_label: "New Password",
    updating: "Updating...",
    update_password_btn: "Update Password",
    phone_number: "+974 1234 5678",

    // Affiliate program
    affiliateApproved: "Affiliate Approved",
    affiliateApprovedDescription: "You are now an approved affiliate. Start earning commissions by referring others!",
    affiliatePending: "Application Pending",
    affiliatePendingDescription: "Your affiliate application is under review. We'll notify you once approved.",
    affiliateNotApproved: "Application Not Approved",
    affiliateNotApprovedDescription: "Your affiliate application was not approved at this time.",
    affiliateRejectionReason: "Reason: {reason}",
    affiliateJoinProgram: "Join Affiliate Program",
    affiliateJoinDescription: "Earn multi-tier commissions by referring others to Nutrio Fuel.",
    affiliateEarnCommissions: "Earn Commissions",
    affiliate3TierRewards: "3-Tier Rewards",
    affiliateMonthlyPayouts: "Monthly Payouts",
    affiliateNotePlaceholder: "Enter any additional information...",
    submitApplication: "Submit Application",
    applyNow: "Apply Now",
    affiliateApplicationSubmitted: "Application Submitted",
    affiliateApplicationSubmittedDescription: "Your affiliate application has been submitted successfully.",
    affiliateApplicationFailed: "Application failed to submit. Please try again.",

    // FAQ
    faq_category_getting_started: "Getting Started",
    faq_category_pricing: "Subscriptions & Pricing",
    faq_category_meals: "Meals & Ordering",
    faq_category_delivery: "Delivery",
    faq_category_nutrition: "Nutrition & Health",
    faq_category_account: "Account & Support",
    faq_getting_started_q1: "How do I create an account?",
    faq_getting_started_a1: "Creating an account is easy! Click 'Get Started' on our homepage, complete the onboarding questionnaire about your health goals, body metrics, and dietary preferences, and you'll have your personalized nutrition plan ready in minutes.",
    faq_getting_started_q2: "How are my daily calorie and macro targets calculated?",
    faq_getting_started_a2: "We use scientifically-backed formulas including your age, gender, height, weight, activity level, and health goals (lose, gain, or maintain weight) to calculate your Basal Metabolic Rate (BMR) and Total Daily Energy Expenditure (TDEE). Your targets are then customized based on your specific goals.",
    faq_getting_started_q3: "Can I update my health goals later?",
    faq_getting_started_a3: "Absolutely! You can update your profile and health goals anytime through your account settings. Your nutrition targets will automatically recalculate based on your new information.",
    faq_pricing_q1: "What subscription plans do you offer?",
    faq_pricing_a1: "We offer two flexible plans: Weekly (QAR 29/week) for those who want to try our service, and Monthly (QAR 89/month) which offers better value with a 23% savings. Both plans include access to all partner restaurants and personalized meal planning.",
    faq_pricing_q2: "Can I cancel my subscription anytime?",
    faq_pricing_a2: "Yes, you can cancel your subscription at any time through your account settings. Your access will continue until the end of your current billing period. We don't offer refunds for partial periods.",
    faq_pricing_q3: "What payment methods do you accept?",
    faq_pricing_a3: "We accept all major credit cards (Visa, MasterCard, American Express), debit cards, and digital payment methods. All payments are processed securely through our payment partner.",
    faq_pricing_q4: "Is there a free trial?",
    faq_pricing_a4: "While we don't offer a traditional free trial, our weekly plan is a great low-commitment way to try the service. You can cancel anytime if it's not right for you.",
    faq_meals_q1: "How do I order meals?",
    faq_meals_a1: "Browse our partner restaurants, filter by dietary preferences, and select meals that fit your nutrition goals. Schedule your meals for breakfast, lunch, or dinner on your preferred dates, and we'll handle the rest!",
    faq_meals_q2: "Can I filter meals by dietary restrictions?",
    faq_meals_a2: "Yes! We offer extensive dietary filters including Keto, Vegan, Vegetarian, Gluten-Free, Dairy-Free, Low-Carb, High-Protein, and more. You can set your preferences in your profile for personalized recommendations.",
    faq_meals_q3: "How far in advance can I schedule meals?",
    faq_meals_a3: "You can schedule meals up to 2 weeks in advance. We recommend scheduling at least 24 hours ahead to ensure restaurant availability and timely preparation.",
    faq_meals_q4: "What if I need to cancel or modify an order?",
    faq_meals_a4: "Orders can be modified or cancelled up to 24 hours before the scheduled delivery time. After that, the meal credit may be forfeited. Contact our support team for assistance with last-minute changes.",
    faq_meals_q5: "How many meals can I order per week?",
    faq_meals_a5: "The number of meals depends on your subscription plan. Check your subscription details in your account to see your weekly meal allowance. Unused meals don't roll over to the next week.",
    faq_delivery_q1: "What are your delivery hours?",
    faq_delivery_a1: "Delivery hours vary by restaurant partner, but typically we deliver between 7 AM and 9 PM. You'll see available delivery windows when scheduling your meals.",
    faq_delivery_q2: "Can I track my delivery?",
    faq_delivery_a2: "Yes! Once your order is confirmed and out for delivery, you can track its status in real-time through the Delivery Tracking page in your account.",
    faq_delivery_q3: "What areas do you deliver to?",
    faq_delivery_a3: "We currently deliver within a 10-mile radius of our partner restaurants. Enter your address during signup to see available restaurants in your area.",
    faq_delivery_q4: "Is there a delivery fee?",
    faq_delivery_a4: "No, delivery is completely FREE on all orders! We believe healthy eating should be accessible to everyone, so we cover all delivery costs. No minimum order value required.",
    faq_nutrition_q1: "How accurate is the nutritional information?",
    faq_nutrition_a1: "Nutritional information is provided by our partner restaurants and calculated based on standard serving sizes. While we strive for accuracy, actual values may vary slightly. Use the information as a guideline for your nutrition planning.",
    faq_nutrition_q2: "Can I track my progress over time?",
    faq_nutrition_a2: "Yes! Our Progress page shows detailed charts of your calorie intake, macronutrient breakdown, and weight changes over time. You can log your daily weight and see trends to stay motivated.",
    faq_nutrition_q3: "Is the nutrition advice from a professional?",
    faq_nutrition_a3: "Our calorie and macro calculations are based on established nutritional science and formulas. However, this is not medical advice. For specific health concerns or conditions, please consult a registered dietitian or healthcare provider.",
    faq_nutrition_q4: "Do you accommodate food allergies?",
    faq_nutrition_a4: "We provide allergen information for all meals when available. However, meals are prepared in commercial kitchens that may handle common allergens. If you have severe allergies, please contact the restaurant directly before ordering.",
    faq_account_q1: "How do I reset my password?",
    faq_account_a1: "Click 'Forgot Password' on the login page and enter your email address. We'll send you a secure link to reset your password. The link expires after 24 hours for security.",
    faq_account_q2: "How can I contact customer support?",
    faq_account_a2: "You can reach our support team through the Support page in your account, by emailing support@nutribox.com, or by calling our helpline. We typically respond within 24 hours.",
    faq_account_q3: "Can I have multiple delivery addresses?",
    faq_account_a3: "Yes! You can save multiple addresses (home, work, etc.) in your account and select the appropriate one when scheduling each meal delivery.",
    faq_account_q4: "How do I refer a friend?",
    faq_account_a4: "Visit the Affiliate Program in your account to get your unique referral code. When friends sign up using your code and place orders, you earn commissions automatically!",
    faq_help_center: "Help Center",
    faq_frequently_asked: "Frequently Asked Questions",
    faq_find_answers: "Find answers to common questions about NUTRIO. Can't find what you're looking for?",
    faq_contact_us: "Contact us",
    faq_still_questions: "Still have questions?",
    faq_support_team: "Our support team is here to help you with any questions or concerns.",
    faq_contact_support: "Contact Support",
    faq_submit_ticket: "Submit a Ticket",
    back_to_profile: "Back to Profile",

    // Cancellation Flow
    cancel_subscription: "Cancel Subscription",
    step_1_of_4: "Step 1 of 4",
    step_2_of_4: "Step 2 of 4",
    step_3_of_4: "Step 3 of 4",
    step_4_of_4: "Step 4 of 4",
    why_are_you_leaving: "Why are you leaving?",
    feedback_helps_improve: "Your feedback helps us improve our service for everyone",
    tell_us_more_optional: "Tell us more (optional)",
    feedback_placeholder: "Your feedback is valuable to us...",
    before_you_go_options: "Before you go, we have some options that might help you stay on track with your health goals.",
    keep_subscription: "Keep Subscription",
    need_a_break: "Need a break instead?",
    pause_keeps_benefits: "Pausing keeps your benefits intact. Perfect for vacations or busy periods.",
    resume_automatically: "Resume automatically",
    pause_subscription: "Pause Subscription",
    no_pause_offers: "No pause offers available",
    what_happens_when_pause: "What happens when you pause?",
    subscription_remains_active: "Your subscription remains active",
    billing_delayed: "Next billing is delayed until you resume",
    meal_credits_safe: "All your meal credits stay safe",
    favorite_meals_available: "Your favorite meals are still available",
    continue_to_cancel: "Continue to Cancel",
    how_about_discount: "How about a discount?",
    special_discount_for_you: "We've applied a special discount just for you. Stay and save!",
    save_percent: "SAVE {percent}%",
    you_save_amount: "You save {amount}!",
    apply_discount: "Apply Discount",
    no_discount_offers: "No discount offers available",
    limited_time_offer: "Limited time offer:",
    discount_only_now: "This discount is only available right now. If you cancel, you won't be able to claim this rate when you resubscribe.",
    final_step_cancel: "Final Step: Cancel Subscription",
    sorry_to_see_you_go: "We're sorry to see you go. Here are your final options.",
    consider_downgrade: "Consider a downgrade instead:",
    switch_to_plan: "Switch to {tier} Plan",
    take_bonus_credits: "Or take bonus credits:",
    accept_bonus: "Accept {amount} QAR Bonus",
    confirm_cancellation: "Confirm Cancellation",
    you_will_lose_access: "You'll lose access to:",
    remaining_meals: "Your remaining {count} meals this cycle",
    all_subscription_benefits: "All subscription benefits",
    discounted_pricing: "Discounted meal pricing",
    priority_delivery: "Priority delivery",
    access_continues_until: "Your access continues until {date}",
    cancelling: "Cancelling...",

    // Cancellation reasons
    reason_too_expensive: "Too expensive",
    reason_too_expensive_desc: "The subscription costs are too high for my budget",
    reason_not_using: "Not using enough",
    reason_not_using_desc: "I'm not ordering enough meals to justify the cost",
    reason_moving: "Moving away",
    reason_moving_desc: "I'm relocating and won't be able to use the service",
    reason_dietary: "Dietary changes",
    reason_dietary_desc: "My dietary needs have changed and don't match the menu",
    reason_quality: "Quality issues",
    reason_quality_desc: "I'm not satisfied with the food quality",
    reason_delivery: "Delivery issues",
    reason_delivery_desc: "Having problems with delivery timing or reliability",
    reason_alternative: "Found alternative",
    reason_alternative_desc: "I've found another meal service that works better",
    reason_temporary: "Temporary break",
    reason_temporary_desc: "I just need a pause and plan to return",
    reason_other: "Other",
    reason_other_desc: "Something else not listed here",
  },

  // ──────────────────────────────────────────────────────────────────────────────

  ar: {
    // Navigation
    nav_home: "الرئيسية",
    nav_restaurants: "المطاعم",
    nav_schedule: "الجدول",
    nav_affiliate: "الشراكة",
    nav_profile: "الملف الشخصي",
    // BMI labels
    normal: "طبيعي",
    overweight: "زيادة وزن",
    obese: "سمنة",
    underweight: "نقص وزن",
    // Tracker
    starting: "البداية",
    // Profile
    save_changes: "حفظ التغييرات",
    profile_settings: "الملف الشخصي والإعدادات",
    when_restaurants_add_items: "عند إضافة المطاعم لعناصر جديدة",
    tailor_meals_offers: "تخصيص الوجبات والعروض حسب عاداتك",
    help_improve_app: "ساعدنا في تحسين التطبيق ببيانات مجهولة",
    notification_settings: "إعدادات الإشعارات",
    // Profile page
    order_updates: "تحديثات الطلبات",
    status_changes_orders: "تغييرات حالة طلباتك النشطة",
    discounts_special_deals: "خصومات وصفقات خاصة",
    choose_notifications: "اختر ما تريد الإشعار به",
    control_data_usage: "تحكم في كيفية استخدام بياناتك",
    manage_account_status: "إدارة حالة حسابك",
    manage_addresses: "إدارة عناوين التوصيل المحفوظة",
    delete_account_warning: "لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع بياناتك بما في ذلك جداول الوجبات وسجلات التقدم والتفضيلات بشكل دائم.",
    // Dashboard
    on_fire_message: "أنت رائع! استمر في تسجيل وجباتك.",
    days_to_milestone: "أيام حتى الهدف التالي",
    days_this_week: "أيام هذا الأسبوع",
    weekly_goal: "الهدف الأسبوعي",
    no_featured_restaurants: "لا توجد مطاعم مميزة حتى الآن",
    check_back_restaurants: "تحقق لاحقاً لمطاعمنا الشريكة المميزة!",
    // Auth & Progress
    on_track_nutrition: "على المسار الصحيح مع خطة تغذيتك",
    eat_smart: "تناول بذكاء،",
    live_better: "عش بشكل أفضل",



    // Common
    save: "حفظ",
    cancel: "إلغاء",
    pay_with_amount: "دفع",
    close: "إغلاق",
    edit: "تعديل",
    delete: "حذف",
    confirm: "تأكيد",
    loading: "جاري التحميل...",
    saving: "جاري الحفظ…",
    search: "بحث",
    filter: "تصفية",
    all: "الكل",
    yes: "نعم",
    no: "لا",
    back: "رجوع",
    next: "التالي",
    submit: "إرسال",
    update: "تحديث",
    add: "إضافة",
    remove: "إزالة",
    view: "عرض",
    share: "مشاركة",
    download: "تنزيل",
    upload: "رفع",
    select: "اختيار",
    change: "تغيير",
    apply: "تطبيق",
    reset: "إعادة تعيين",
    clear: "مسح",
    ok: "موافق",
    error: "خطأ",
    success: "نجاح",
    warning: "تحذير",
    info: "معلومة",
    retry: "إعادة المحاولة",
    reload: "إعادة تحميل",
    processing: "جاري المعالجة...",

    // Dashboard
    good_morning: "صباح الخير ☀️",
    good_afternoon: "مساء الخير 🌤️",
    good_evening: "مساء النور 🌙",
    todays_progress: "تقدم اليوم",
    calories: "السعرات الحرارية",
    protein: "البروتين",
    carbs: "الكربوهيدرات",
    fat: "الدهون",
    water: "الماء",
    steps: "الخطوات",
    weight: "الوزن",
    goal: "الهدف",
    nutrition_eaten: "التغذية المتناولة",
    nutrition_cal: "سعرة",
    streak: "الاستمرارية",
    days: "أيام",
    day: "يوم",
    week: "أسبوع",
    month: "شهر",
    year: "سنة",
    today: "اليوم",
    yesterday: "أمس",
    weekly: "أسبوعي",
    monthly: "شهري",
    yearly: "سنوي",
    view_all: "عرض الكل",
    see_all: "مشاهدة الكل",
    no_data: "لا توجد بيانات",
    sign_out: "تسجيل الخروج",
    signed_out: "تم تسجيل الخروج",
    signed_out_desc: "تم تسجيل خروجك بنجاح.",

    // Meals / Restaurants
    restaurants: "المطاعم",
    meals: "الوجبات",
    meal: "وجبة",
    breakfast: "الإفطار",
    lunch: "الغداء",
    dinner: "العشاء",
    snack: "وجبة خفيفة",
    search_food: "ابحث عن طعام...",
    search_restaurants: "ابحث عن مطاعم...",
    all_restaurants: "جميع المطاعم",
    your_favorites: "المفضلة لديك",
    favorite_meals: "الوجبات المفضلة",
    no_restaurants_found: "لم يتم العثور على مطاعم",
    no_meals_found: "لم يتم العثور على وجبات",
    no_favorites_yet: "لا توجد مفضلات بعد",
    no_favorite_meals_yet: "لا توجد وجبات مفضلة بعد",
    available_now: "متاح الآن",
    currently_unavailable: "غير متاح حالياً",
    delicious_healthy_meals: "وجبات صحية ولذيذة",
    healthy_and_delicious: "وجبات صحية ولذيذة",
    fastest: "الأسرع",
    popular: "الأكثر شعبية",
    top_rated: "الأعلى تقييماً",
    favorites: "المفضلة",
    filters: "الفلاتر",
    under_300: "أقل من 300",
    add_to_cart: "أضف إلى السلة",
    order_now: "اطلب الآن",
    calories_kcal: "السعرات الحرارية (kcal)",
    kcal: "سعرة",
    g: "غ",
    ml: "مل",
    cups: "أكواب",
    kg: "كغ",
    cm: "سم",

    // Schedule
    schedule: "الجدول",
    set_delivery_time: "تحديد وقت التوصيل",
    delivery_time_set: "تم تحديد وقت التوصيل",

    // Progress / Tracker
    progress: "التقدم",
    tracker: "المتتبع",
    insights: "التحليلات",
    bmi: "مؤشر كتلة الجسم",
    edit_bmi: "تعديل مؤشر كتلة الجسم",
    height: "الطول",
    add_steps: "إضافة خطوات",
    step_goal: "هدف الخطوات",
    water_intake: "استهلاك الماء",
    weight_goal: "هدف الوزن",
    calorie_goal: "هدف السعرات",
    protein_goal: "هدف البروتين",
    log_meal: "تسجيل وجبة",
    log_activity: "تسجيل نشاط",
    weekly_report: "التقرير الأسبوعي",
    download_report: "تنزيل التقرير",
    generating_report: "جاري إنشاء التقرير...",
    report_downloaded: "تم تنزيل التقرير!",
    report_failed: "فشل إنشاء التقرير",
    scan_food: "مسح الطعام",
    take_photo: "التقاط صورة",
    upload_from_gallery: "رفع من المعرض",
    scan_your_food: "امسح طعامك",
    scan_desc: "التقط صورة أو ارفع من معرضك لتحديد الطعام وتسجيله فوراً.",
    recent: "الأخيرة",
    manual_log: "تسجيل يدوي",
    select_items_to_add: "اختر العناصر للإضافة",
    use_camera_to_capture: "استخدم الكاميرا لالتقاط الطعام",
    pick_existing_photo: "اختر صورة موجودة",

    // Profile / Settings
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    profile_and_settings: "الملف الشخصي والإعدادات",
    personal_info: "المعلومات الشخصية",
    account_actions: "إجراءات الحساب",
    manage_account: "إدارة حالة حسابك",
    delete_account: "حذف الحساب",
    language: "اللغة",
    select_language: "اختر لغتك المفضلة",
    english: "English",
    arabic: "العربية",
    notifications: "الإشعارات",
    privacy_settings: "إعدادات الخصوصية",
    control_data: "تحكم في كيفية استخدام بياناتك",
    usage_analytics: "تحليلات الاستخدام",
    usage_analytics_desc: "ساعدنا في تحسين التطبيق ببيانات مجهولة",
    personalised_recommendations: "توصيات مخصصة",
    personalised_desc: "تخصيص الوجبات والعروض وفق عاداتك",
    new_meals_available: "وجبات جديدة متاحة",
    new_meals_desc: "عندما تضيف المطاعم عناصر جديدة",
    promotions_offers: "العروض والخصومات",
    promotions_desc: "الخصومات والصفقات الخاصة",
    profile_updated: "تم تحديث الملف الشخصي",
    personal_info_saved: "تم حفظ معلوماتك الشخصية.",
    password_updated: "تم تحديث كلمة المرور",
    passwords_dont_match: "كلمات المرور غير متطابقة",
    password_min_length: "يجب أن تكون كلمة المرور 6 أحرف على الأقل.",
    contact_support: "التواصل مع الدعم",
    view_affiliate_dashboard: "عرض لوحة الشراكة",
    apply_affiliate: "التقدم لبرنامج الشراكة",

    // Profile related (missing)
    profile_details: "تفاصيل الملف الشخصي",
    update_your_profile_details: "تحديث تفاصيل ملفك الشخصي",
    update_profile_details: "تحديث تفاصيل الملف الشخصي",
    update_profile_button: "تحديث الملف الشخصي",
    saving_now: "جاري الحفظ...",
    profile_updated_success: "تم تحديث الملف الشخصي",
    personal_info_saved_success: "تم حفظ معلوماتك الشخصية.",
    error_saving_profile: "خطأ في حفظ الملف الشخصي",
    failed_load_dietary_preferences: "فشل تحميل التفضيلات الغذائية",
    removed: "تمت الإزالة",
    added: "تمت الإضافة",
    failed_update_dietary_preference: "فشل تحديث التفضيل الغذائي",
    passwords_match_warning: "يرجى التأكد من تطابق كلمات المرور الجديدة.",
    password_changed_success: "تم تغيير كلمة المرور بنجاح.",
    error_updating_password: "خطأ في تحديث كلمة المرور",
    contact_support_delete_account: "يرجى التواصل مع الدعم لحذف حسابك.",
    successful: "نجاح",
    please_try_again: "يرجى المحاولة مرة أخرى.",
    password_too_short: "كلمة المرور قصيرة جداً",
    password_must_be_at_least_6_characters: "يجب أن تكون كلمة المرور 6 أحرف على الأقل.",
    password_updated_description: "تم تغيير كلمة المرور بنجاح.",
    updated_successfully: "تم التحديث بنجاح",
    added_successfully: "تمت الإضافة بنجاح",
    removed_successfully: "تمت الإزالة بنجاح",
    gender: "الجنس",
    age: "العمر",

    // Auth
    sign_in: "تسجيل الدخول",
    sign_up: "إنشاء حساب",
    create_free_account: "إنشاء حساب مجاني",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgot_password: "نسيت كلمة المرور؟",
    reset_password: "إعادة تعيين كلمة المرور",
    can_reset_password: "يمكنك الآن إعادة تعيين كلمة المرور.",
    dont_have_account: "ليس لديك حساب؟",
    already_have_account: "لديك حساب بالفعل؟",

    // Goals
    weight_loss: "خسارة الوزن",
    muscle_gain: "بناء العضلات",
    maintenance: "الحفاظ على الوزن",
    general_health: "الصحة العامة",
    not_enough_data: "لا توجد بيانات كافية بعد",
    no_active_goal: "لا يوجد هدف نشط",
    set_nutrition_goal: "حدد هدفاً غذائياً أولاً حتى نتمكن من تحليل تقدمك.",
    goal_optimization: "تحسين الهدف بناءً على بياناتك",

    // Wallet / Orders
    wallet: "المحفظة",
    order_history: "سجل الطلبات",
    invoice_history: "سجل الفواتير",
    checkout: "الدفع",
    total: "الإجمالي",
    subtotal: "المجموع الفرعي",
    delivery_fee: "رسوم التوصيل",
    discount: "الخصم",
    payment: "الدفع",
    place_order: "تأكيد الطلب",

    // Wallet related (missing)
    available_balance: "الرصيد المتاح",
    available_for_orders: "متاح للطلبات",
    total_spent: "إجمالي الإنفاق",
    total_credits: "إجمالي الرصيد",
    you_get: "تحصل على",
    credits_never_expire: "الرصيد لا ينتهي أبداً",
    transaction_history: "سجل المعاملات",
    no_transactions_yet: "لا توجد معاملات بعد",
    top_up_wallet_start: "أعد شحن محفظتك للبدء",
    secure_payment_sadad: "دفع آمن عبر سداد",
    commission_balance: "رصيد العمولة",
    recent_commissions: "العمولات الأخيرة",
    tier: "المستوى",
    available: "متاح",
    total_earned: "إجمالي المكتسب",
    top_up_packages: "باقات إعادة الشحن",
    get_bonus_credits_desc: "احصل على رصيد إضافي عند إعادة الشحن",

    // Addresses
    addresses: "العناوين",
    add_address: "إضافة عنوان",
    delivery_address: "عنوان التوصيل",

    // Subscription
    subscription: "الاشتراك",
    subscribe: "اشترك",
    current_plan: "الخطة الحالية",
    upgrade: "ترقية",

    // Support / About
    support: "الدعم",
    about: "حول",
    faq: "الأسئلة الشائعة",
    contact: "تواصل معنا",
    privacy_policy: "سياسة الخصوصية",
    terms: "الشروط والأحكام",
    policies: "السياسات",

    // Notifications
    notification: "إشعار",
    mark_all_read: "تحديد الكل كمقروء",
    no_notifications: "لا توجد إشعارات",

    // Water tracker
    add_water: "إضافة ماء",
    water_goal: "هدف الماء",
    glasses: "أكواب",
    liters: "لتر",

    // Weight tracking
    log_weight: "تسجيل الوزن",
    update_weight: "تحديث الوزن",
    weight_updated: "تم تحديث الوزن",
    weight_logged: "كغ تم تسجيله.",
    failed_to_update: "فشل التحديث",
    water_added: "تمت إضافة الماء",

    // Step counter
    step_counter: "عداد الخطوات",
    steps_today: "خطوات اليوم",
    distance: "المسافة",
    active_time: "وقت النشاط",

    // Onboarding
    get_started: "ابدأ الآن",
    skip: "تخطي",
    continue: "متابعة",
    done: "تم",
    welcome: "مرحباً",
    welcome_to_nutrio: "مرحباً بك في نوتريو",
    fuel_your_body: "غذِّ جسمك بذكاء",

    // Errors
    something_went_wrong: "حدث خطأ ما",
    we_apologize: "نعتذر عن الإزعاج. تم الإبلاغ عن الخطأ وسنصلحه قريباً.",
    reload_page: "إعادة تحميل الصفحة",
    not_found: "الصفحة غير موجودة",
    go_home: "الذهاب للرئيسية",

    // Time zones
    timezone_qatar: "قطر (GMT +3)",

    // Gender
    he_him: "هو/له",
    she_her: "هي/لها",

    // Expected impact
    expected_impact: "التأثير المتوقع",
    hide_impact: "إخفاء التأثير",

    // Show results
    show_results: "عرض",
    restaurants_label: "مطاعم",
    meals_label: "وجبات",

    // Report
    overall_score: "النتيجة الإجمالية",
    weekly_performance: "الأداء الأسبوعي",
    habit_intelligence: "وذكاء العادات",
    weekly_report_title: "التقرير الأسبوعي",
    prepared_for: "معد لـ",
    generated: "تم الإنشاء",

    // Auth page
    personalized_plans: "خطط مخصصة",
    calorie_macro_tracking: "تتبع السعرات والمغذيات",
    restaurant_integration: "تكامل المطاعم",
    progress_insights: "التقدم والتحليلات",
    welcome_feature_desc: "احصل على خطط وجبات مصممة لأهدافك وتفضيلاتك الغذائية ونمط حياتك.",
    create_account: "إنشاء حساب",
    full_name: "الاسم الكامل",
    confirm_password: "تأكيد كلمة المرور",
    verify_email: "تحقق من بريدك الإلكتروني",
    otp_sent_to: "أرسلنا رمزاً مكوناً من 6 أرقام إلى",
    enter_otp: "أدخل الرمز المكون من 6 أرقام",
    verify_code: "التحقق من الرمز",
    resend_code: "إعادة إرسال الرمز",
    back_to_signup: "العودة للتسجيل",
    send_reset_link: "إرسال رابط الاستعادة",
    back_to_signin: "العودة لتسجيل الدخول",
    sign_in_required: "تسجيل الدخول مطلوب",
    sign_in_required_desc: "يرجى تسجيل الدخول أو إنشاء حساب للمتابعة.",
    complete: "إتمام",
    male: "ذكر",
    female: "أنثى",
    prefer_not_to_say: "أفضل عدم الإجابة",

    // Onboarding
    lose_weight: "إنقاص الوزن",
    lose_weight_desc: "تقليل الدهون مع الحفاظ على العضلات",
    build_muscle: "بناء العضلات",
    build_muscle_desc: "اكتساب كتلة عضلية بتغذية مناسبة",
    maintain: "الحفاظ على الوزن",
    maintain_desc: "الحفاظ على وزنك الحالي وتحسين صحتك",
    maintenance_goal: "الحفاظ على الوزن",
    sedentary: "خامل",
    sedentary_desc: "نشاط بدني قليل أو معدوم",
    lightly_active: "نشط قليلاً",
    lightly_active_desc: "تمارين خفيفة 1-3 أيام/أسبوع",
    moderately_active: "نشط بشكل معتدل",
    moderately_active_desc: "تمارين معتدلة 3-5 أيام/أسبوع",
    very_active: "نشط جداً",
    very_active_desc: "تمارين شاقة 6-7 أيام/أسبوع",
    extra_active: "نشط بشكل استثنائي",
    extra_active_desc: "تمارين شاقة جداً وعمل بدني",

    // Main Menu
    food_and_meals: "الطعام والوجبات",
    plan_weekly_meals: "خطط وجباتك الأسبوعية",
    browse_all_restaurants: "تصفح جميع المطاعم",
    progress_and_goals: "التقدم والأهداف",
    track_weight_nutrition: "تتبع الوزن والتغذية ومقاييس الصحة",
    updated: "محدّث",
    orders_and_subscription: "الطلبات والاشتراك",
    view_past_orders: "عرض الطلبات السابقة",
    manage_your_plan: "إدارة خطتك",
    upgrade_your_plan: "ترقية خطتك",
    live_tracking: "التتبع المباشر",
    track_your_orders: "تتبع طلباتك",
    settings_and_account: "الإعدادات والحساب",
    personal_info_preferences: "المعلومات الشخصية والتفضيلات",
    app_preferences: "تفضيلات التطبيق",
    delivery_locations: "مواقع التوصيل",
    earn_rewards: "اكسب مكافآت",
    earn_with_audience: "اكسب مع جمهورك",
    affiliate: "الشراكة",
    menu: "القائمة",
    saved_restaurants: "مطاعم محفوظة",

    // MealWizard
    snacks_salad: "وجبات خفيفة وسلطات",
    breakfast_desc: "ابدأ يومك بطاقة",
    lunch_desc: "أمدّ نشاطك بعد الظهر",
    dinner_desc: "اختم يومك بشكل صحيح",
    snacks_desc: "إضافات صحية",
    back_to_restaurants: "العودة للمطاعم",
    partner_restaurant: "مطعم شريك",

    // Progress page
    great: "ممتاز",
    good: "جيد",
    keep_going: "واصل",
    first_week_complete: "اكتملت الأسبوع الأول",
    logged_meals_7_days: "سجّلت وجبات لمدة 7 أيام",
    protein_pro: "محترف البروتين",
    hit_protein_goal_5_days: "حققت هدف البروتين 5 أيام",
    hydration_hero: "بطل الترطيب",
    drank_8_glasses: "شربت 8 أكواب لمدة أسبوع",
    analyzing_21_days: "تحليل آخر 21 يوماً…",
    log_meals_4_days: "سجّل وجباتك لمدة 4 أيام على الأقل لفتح الاقتراحات المخصصة.",
    set_nutrition_goal_first: "حدد هدفاً غذائياً أولاً حتى نتمكن من تحليل تقدمك.",
    high_confidence_changes: "تغييرات عالية الثقة",
    high_confidence: "ثقة عالية",
    suggestion: "اقتراح",
    exploratory: "استكشافي",
    safety_tip: "نصيحة أمان",

    // Meals Remaining Widget
    unlimited: "غير محدود",
    running_low_meals: "تنفذ الوجبات! تبقت {count} فقط. اختر وجباتك القادمة بحكمة.",
    getting_low_meals: "تنفذ الوجبات. لديك {remaining} من أصل {total}.",

    // TrackerInsights
    smart_adjustments: "تعديلات ذكية",
    suggestions_based_on: "اقتراحات بناءً على",

    // LogMealDialog
    log_food: "تسجيل طعام",
    search_food_items: "ابحث عن أصناف الطعام...",
    quick_log: "تسجيل سريع",
    my_meals: "وجباتي",
    food_name: "اسم الطعام",
    amount: "الكمية",
    unit: "الوحدة",
    add_food: "إضافة طعام",
    nutrition_info: "المعلومات الغذائية",
    per_serving: "لكل حصة",
    add_to_log: "إضافة للسجل",
    serving_size: "حجم الحصة",

    // Schedule page
    meal_schedule: "جدول الوجبات",
    plan_your_meals: "خطط وجباتك للأسبوع",
    add_meal: "إضافة وجبة",
    no_meals_scheduled: "لا توجد وجبات مجدولة",
    delivery_timezone: "منطقة التوصيل الزمنية",

    // Profile page
    he_him_pronoun: "هو/له",
    she_her_pronoun: "هي/لها",
    your_name: "اسمك",
    enter_email: "أدخل بريدك الإلكتروني",
    nutrition_goals: "الأهداف الغذائية",
    daily_calories: "السعرات اليومية",
    daily_protein: "البروتين اليومي",
    daily_carbs: "الكربوهيدرات اليومية",
    daily_fat: "الدهون اليومية",

    // Auth page (missing keys)
    welcome_back: "مرحباً بعودتك",
    signin_desc: "سجّل الدخول إلى حساب نوتريو",
    remember_me: "تذكرني",
    signing_in: "جاري تسجيل الدخول...",
    join_nutrio_today: "انضم إلى نوتريو اليوم",
    create_account_desc: "ابدأ رحلتك الغذائية المخصصة",
    i_agree_to_nutrio: "أوافق على شروط نوتريو",
    creating_account: "جاري إنشاء الحساب...",
    personalized_nutrition_tagline: "تتبع، كُل، وعش بذكاء كل يوم.",
    feature_personalized_plans: "خطط مخصصة",
    feature_personalized_plans_desc: "احصل على خطط وجبات مصممة لأهدافك واحتياجاتك الغذائية.",
    feature_restaurant_partners: "المطاعم الشريكة",
    feature_restaurant_partners_desc: "اطلب من مجموعة مختارة من المطاعم الصحية.",
    feature_track_progress: "تتبع التقدم",
    feature_track_progress_desc: "راقب سعراتك ومغذياتك ومقاييس لياقتك يومياً.",
    enter_otp_code: "تحقق من بريدك الإلكتروني",
    otp_sent_desc: "أرسلنا رمزاً مكوناً من 6 أرقام إلى بريدك الإلكتروني.",
    resend_code_in: "إعادة إرسال الرمز بعد",
    seconds: "ثانية",
    verifying: "جاري التحقق...",
    verify_otp: "تحقق من الرمز",
    forgot_password_desc: "أدخل بريدك المسجل لاستلام رابط إعادة تعيين كلمة المرور.",
    registered_email: "البريد المسجل",
    sending: "جاري الإرسال...",
    send_otp_code: "إرسال رابط الاستعادة",

    // Profile tabs (sidebar nav)
    profile_tab: "الملف الشخصي",
    rewards: "المكافآت",

    // Profile form placeholders
    enter_full_name: "أدخل اسمك الكامل",
    enter_new_password: "أدخل كلمة المرور الجديدة",
    confirm_new_password: "تأكيد كلمة المرور الجديدة",
    apply_affiliate_program: "التقدم لبرنامج الشراكة",

    // Schedule page
    sign_in_to_schedule: "سجّل الدخول لعرض الجدول",
    sign_in_to_schedule_desc: "يرجى تسجيل الدخول لعرض وإدارة جدول وجباتك.",
    swipe_to_change_week: "اسحب لتغيير الأسبوع",
    schedule_delivery: "جدولة التوصيل",

    // TrackerInsights charts
    calorie: "السعرة الحرارية",
    calorie_kcal: "السعرات الحرارية (kcal)",
    calorie_intake_goal: "هدف السعرات",
    water_ml: "الماء (مل)",
    water_intake_goal: "هدف استهلاك الماء",
    weight_kg: "الوزن (كغ)",
    log_more_weight: "سجّل مزيداً من قراءات الوزن لعرض الاتجاهات",
    set_height_weight_bmi: "حدد طولك ووزنك لعرض مؤشر كتلة الجسم",
    selected: "المحدد",

    // LogMealDialog
    analyzing_food: "جاري تحليل الطعام",
    ai_detecting_ingredients: "الذكاء الاصطناعي يكتشف المكونات...",
    items_detected: "عناصر مكتشفة",
    item_detected: "عنصر مكتشف",
    scan_again: "مسح مرة أخرى",
    scan_food_desc: "التقط صورة أو ارفع من معرضك لتحديد الطعام وتسجيله فوراً.",
    total_weight: "الوزن الإجمالي",
    todays_schedule: "جدول اليوم",
    no_recent_meals: "لا توجد وجبات حديثة",
    no_results_for: "لا نتائج لـ",
    try_quick_log: "جرّب التسجيل السريع",
    recently_logged: "سُجّل مؤخراً",
    items: "عناصر",
    item: "عنصر",
    food_name_placeholder: "مثال: دجاج مشوي",
    log: "تسجيل",
    create_food: "إنشاء طعام",

    // Profile page extensions
    loading_profile: "جاري تحميل الملف الشخصي...",
    free_plan: "الخطة المجانية",
    joined: "انضمام",
    profile_updated_description: "تم حفظ معلوماتك الشخصية.",
    dietary_preference_removed: "تمت إزالة التفضيل الغذائي",
    dietary_preference_added: "تمت إضافة التفضيل الغذائي",
    dietary_preference_removed_description: "تمت إزالته بنجاح",
    dietary_preference_added_description: "تمت إضافته بنجاح",
    personal_info_desc: "الاسم والجنس والعمر وعنوان البريد الإلكتروني",
    full_name_label: "الاسم الكامل",
     years_label: "سنوات",
     age_label: "العمر",
     age_default_placeholder: "25",
     email_address: "عنوان البريد الإلكتروني",
    manage_addresses_action: "إدارة العناوين",
    delivery_addresses: "عناوين التوصيل",
    dietary_and_allergies: "التغذية والحساسية",
    manage_dietary_preferences: "إدارة تفضيلاتك الغذائية والحساسيات",
    dietary_preferences: "التفضيلات الغذائية",
    no_dietary_tags_available: "لا توجد علامات غذائية متاحة",
    allergies_and_intolerances: "الحساسية وعدم التحمل",
    terms_and_conditions: "الشروط والأحكام",
    privacy_policy_label: "سياسة الخصوصية",
    get_help_report_issues: "احصل على المساعدة أو أبلغ عن مشكلة أو اتصل بنا",
    chat_on_whatsapp: "دردشة على واتسآب",
    email_support: "دعم البريد الإلكتروني",
    call_us: "اتصل بنا",
    submit_a_ticket: "إرسال تذكرة",
    view_faq: "عرض الأسئلة الشائعة",
    support_hours: "نوتريو فويل · ساعات الدعم: 8 صباحاً – 10 مساءً (قطر)",
    my_wallet: "محفظتي",
    top_up_manage_balance: "أعادة الشحن وإدارة الرصيد",
    payment_successful: "تم الدفع بنجاح! تم ائتمان محفظتك.",
    payment_failed: "فشل الدفع. يرجى المحاولة مرة أخرى.",
    simulation_mode: "وضع المحاكاة: جميع المدفوعات محاكاة. لن يتم خصم أي أموال حقيقية.",
    confirm_top_up: "تأكيد إعادة الشحن",
    review_top_up_details: "راجع تفاصيل إعادة الشحن الخاصة بك قبل المتابعة للدفع.",
    package_label: "الباقة",
    top_up_amount: "مبلغ إعادة الشحن",
    bonus_credit: "ائتمان إضافي",
    total_credit: "إجمالي الائتمان",
    bonus: "مكافأة",
    credit: "ائتمان",
    debit: "مدين",
    refund: "استرداد",
    cashback: "نقدية",
    redirected_to_sadad: "سيتم توجيهك إلى سداد لإكمال الدفع بأمان.",
    daily_streaks: "الاستمرارية اليومية",
    order_daily_earn_bonuses: "اطلب يومياً لكسب أرصدة إضافية",
    wallet_bonuses: "مكافآت المحفظة",
    get_bonus_credits: "احصل على أرصدة إضافية عند الشحن",
    affiliate_program: "برنامج الشراكة",
    earn_more: "اربح المزيد",
    referrals: "إحالات",
    become_affiliate: "كن شريكاً واربح عمولات متعددة المستويات (حتى 3 مستويات) من مراجعاتك.",
    change_password: "تغيير كلمة المرور",
    update_account_password: "تحديث كلمة مرور حسابك",
    new_password_label: "كلمة المرور الجديدة",
    updating: "جاري التحديث...",
    update_password_btn: "تحديث كلمة المرور",
    phone_number: "+974 1234 5678",

    // Streak Rewards (missing)
    streakRewardTitle: "مكافأة الاستمرارية",
    rewardClaimed: "تم استلام المكافأة",
    walletCreditApplied: "تم تطبيق رصيد المحفظة",
    earnedReward: "مكافأة مكتسبة",
    failedToClaimReward: "فشل استلام المكافأة",
    nextReward: "المكافأة التالية",
    daysToUnlock: "{days} أيام لفتح {reward}",
    availableRewards: "المكافآت المتاحة",
    dayStreak: "يوم استمرارية",
    claim: "استلام",
    noRewardsAvailable: "لا توجد مكافآت متاحة",
    upcoming: "قادم",
    allRewardsUnlocked: "تم فتح جميع المكافآت",

    // Affiliate Milestones (missing)
    affiliate_milestone_bonuses: "مكافآت معالم الإحالة",
    affiliate_unlocked: "تم الفتح",
    affiliate_progress_to: "التقدم نحو",
    affiliate_more_referrals: "إحالات إضافية",
    affiliate_more_referral: "إحالة إضافية",
    affiliate_to_earn: "للكسب",
    affiliate_bonus: "مكافأة",
    affiliate_total_milestone_bonuses_earned: "إجمالي مكافآت المعالم المكتسبة",
    affiliate_achieved: "تم تحقيق",
    affiliate_next_goal: "الهدف التالي",
    secure_payment_sadad_credits_never_expire: "دفع آمن عبر سداد • الرصيد لا ينتهي",

    // برنامج الشراكة
    affiliateApproved: "شريك معتمد",
    affiliateApprovedDescription: "أنت الآن شريك معتمد. ابدأ كسب العمولات من خلال إحالة الآخرين!",
    affiliatePending: "التطبيق قيد الانتظار",
    affiliatePendingDescription: "تطبيق الشراكة الخاص بك قيد المراجعة. سنخطرك بمجرد الموافقة.",
    affiliateNotApproved: "التطبيق غير موافق عليه",
    affiliateNotApprovedDescription: "لم يتم الموافقة على طلب الشراكة الخاص بك في هذا الوقت.",
    affiliateRejectionReason: "السبب: {reason}",
    affiliateJoinProgram: "انضم لبرنامج الشراكة",
    affiliateJoinDescription: "اكسب عمولات متعددة المستويات من خلال إحالة الآخرين إلى نوتريو فويل.",
    affiliateEarnCommissions: "اكسب عمولات",
    affiliate3TierRewards: "مكافآت 3 مستويات",
    affiliateMonthlyPayouts: "مدفوعات شهرية",
    affiliateNotePlaceholder: "أدخل أي معلومات إضافية...",
    submitApplication: "إرسال التطبيق",
    applyNow: "تقدم الآن",
    affiliateApplicationSubmitted: "تم إرسال التطبيق",
    affiliateApplicationSubmittedDescription: "تم إرسال طلب الشراكة الخاص بك بنجاح.",
    affiliateApplicationFailed: "فشل إرسال التطبيق. يرجى المحاولة مرة أخرى.",

    // FAQ
    faq_category_getting_started: "البدء",
    faq_category_pricing: "الاشتراكات والتسعير",
    faq_category_meals: "الوجبات والطلب",
    faq_category_delivery: "التوصيل",
    faq_category_nutrition: "التغذية والصحة",
    faq_category_account: "الحساب والدعم",
    faq_getting_started_q1: "كيف أنشئ حساباً؟",
    faq_getting_started_a1: "يسهل إنشاء حساب! اضغط على 'ابدأ الآن' في صفحتنا الرئيسية، وأنشئ استبيان الترحيب حول أهدافك الصحية ومقاييس جسمك وتفضيلاتك الغذائية، وستحصل على خطة التغذية الشخصية الخاصة بك جاهزة في دقائق.",
    faq_getting_started_q2: "كيف يتم حساب أهدافي اليومية من السعرات والماكروز؟",
    faq_getting_started_a2: "نستخدم صيغ مدعومة علمياً تشمل عمرك وجنسك وطولك ووزنك ومستوى نشاطك وأهدافك الصحية (خسارة أو زيادة أو الحفاظ على الوزن) لحساب معدل الأيض الأساسي (BMR) ومعدل الإنفاق الطاقي اليومي الإجمالي (TDEE). ثم يتم تخصيص أهدافك بناءً على أهدافك الخاصة.",
    faq_getting_started_q3: "هل يمكنني تحديث أهدافي الصحية لاحقاً؟",
    faq_getting_started_a3: "بالتأكيد! يمكنك تحديث ملفك الشخصي وأهدافك الصحية في أي وقت من إعدادات حسابك. سيتم إعادة حساب أهدافك الغذائية تلقائياً بناءً على معلوماتك الجديدة.",
    faq_pricing_q1: "ما=line plans do you offer?",
    faq_pricing_a1: "نقدم خطتين مرنتين: أسبوعي (29 ر.ق/أسبوع) للراغبين في تجربة خدماتنا، وشهري (89 ر.ق/شهر) который يوفر قيمة أفضل مع توفير 23%. كلا الخطتين يتضمنان وصولاً إلى جميع المطاعم الشريكة والتخطيط الشخصي للوجبات.",
    faq_pricing_q2: "هل يمكنني إلغاء اشتراكي في أي وقت؟",
    faq_pricing_a2: "نعم، يمكنك إلغاء اشتراكك في أي وقت من إعدادات حسابك. سيستمر وصولك حتى نهاية فترة الفوترة الحالية. لا نقدم استرداداً للمبالغ عن الفترات الجزئية.",
    faq_pricing_q3: "ما هي طرق الدفع التي تقبلونها؟",
    faq_pricing_a3: "نقبل جميع بطاقات الائتمان الرئيسية (visa، MasterCard، American Express)، وبطاقات الخصم، وطرق الدفع الرقمية. يتم معالجة جميع المدفوعات بشكل آمن من خلال شريك الدفع الخاص بنا.",
    faq_pricing_q4: "هل يوجد تجربة مجانية؟",
    faq_pricing_a4: "رغم أننا لا نقدم تجربة مجانية تقليدية، فإن خطتنا الأسبوعية تمثل طريقة ممتازة لتجربة الخدمة دون التزام كبير. يمكنك الإلغاء في أي وقت إذا لم تناسبك.",
    faq_meals_q1: "كيف أطلب الوجبات؟",
    faq_meals_a1: "تصفح مطاعمنا الشريكة، وفّل حسب التفضيلات الغذائية، واختر وجبات تتناسب مع أهدافك الغذائية. خطط وجباتك للإفطار أو الغداء أو العشاء في التواريخ المفضلة لديك، وسنقوم بالباقي!",
    faq_meals_q2: "هل يمكنني تصفية الوجبات حسب القيود الغذائية؟",
    faq_meals_a2: "نعم! نقدم فلاتر غذائية واسعة تشمل الكيتو، والنباتي، والنباتي غير الحيواني، وخلو الغلوتين، وخلو الحليبية، وقليل الكربوهيدرات، وعالٍ البروتين، والمزيد. يمكنك تعيين تفضيلاتك في ملفك الشخصي للحصول على توصيات مخصصة.",
    faq_meals_q3: "كم مقدماً يمكنني جدولة الوجبات؟",
    faq_meals_a3: "يمكنك جدولة الوجبات مقدماً حتى أسبوعين. نوصي بالحجز قبل 24 ساعة على الأقل لضمان توفر المطعم والتدريب في الوقت المناسب.",
    faq_meals_q4: "ماذا عليّ فعله إذا أردت إلغاء أو تعديل طلب؟",
    faq_meals_a4: "يمكن تعديل أو إلغاء الطلبات حتى 24 ساعة قبل وقت التوصيل المجدول. بعد ذلك، قد تضيعائمة الوجبة. اتصل بفريق الدعم الخاص بنا للحصول على مساعدة في التغييرات في اللحظة الأخيرة.",
    faq_meals_q5: "كم عدد الوجبات التي يمكنني طلبها أسبوعياً؟",
    faq_meals_a5: "يعتمد عدد الوجبات على خطة اشتراكك. راجع تفاصيل اشتراكك في حسابك لرؤية مخصصك الأسبوعي من الوجبات. لا تنتقل الوجبات الزائدة إلى الأسبوع القادم.",
    faq_delivery_q1: "ما هي ساعات التوصيل؟",
    faq_delivery_a1: "تختلف ساعات التوصيل حسب مطعم شريك، ولكن عادة نقوم بالتوصيل بين 7 صباحاً و9 مساءً. سترى نوافذ التوصيل المتاحة عند جدولة وجباتك.",
    faq_delivery_q2: "هل يمكنني تتبع التوصيل الخاص بي؟",
    faq_delivery_a2: "نعم! بمجرد تأكيد طلبك وخروج配送 للتوصيل، يمكنك تتبع حالته في الوقت الفعلي من خلال صفحة تتبع التوصيل في حسابك.",
    faq_delivery_q3: "إلى أي مناطق توصّلون؟",
    faq_delivery_a3: "نقوم بالتوصيل حالياً ضمن نصف قطر 10 أميال من مطاعمنا الشريكة. أدخل عنوانك عند التسجيل لرؤية المطاعم المتاحة في منطقتك.",
    faq_delivery_q4: "هل هناك رسوم توصيل؟",
    faq_delivery_a4: "لا، التوصيل مجاني تماماً على جميع الطلبات! نؤمن بأن التغذية السليمة يجب أن تكون في متناول الجميع، لذا نغطي جميع تكاليف التوصيل. لا يوجد حد أدنى لقيمة الطلب.",
    faq_nutrition_q1: "ما مدى دقة المعلومات الغذائية؟",
    faq_nutrition_a1: "تُقدّم المعلومات الغذائية من قِبل المطاعم الشريكةของเรา وتُحسب بناءً على أحجام الحصص القياسية. ورغم سعينا للدقة، قد تختلف القيم الفعلية قليلاً. استخدم المعلومات كإرشاد لتخطيطك الغذائي.",
    faq_nutrition_q2: "هل يمكنني تتبع تقدمي بمرور الوقت؟",
    faq_nutrition_a2: "نعم! تُظهر صفحة التقدم لدينا رسوماً بيانية مفصلة لاستهلاكك من السعرات والتفصيل المغذيات và تغييرات وزنك بمرور الوقت. يمكنك تسجيل وزنك اليومي ورؤية الاتجاهات للحفاظ على الحافز.",
    faq_nutrition_q3: "هل النصيحة الغذائية من محترف؟",
    faq_nutrition_a3: "تعتمد حسابات السعرات والماكروز الخاصة بنا على العلوم والتفسيرات الغذائية المعتمدة. ومع ذلك، فإنها ليست نصيحة طبية. بالنسبة للاهتمامات الصحية أو الحالات الخاصة، يرجى استشارة أخصائي تغذية مسجل أو مقدم رعاية صحية.",
    faq_nutrition_q4: "هل تأخذون في الاعتبار حساسية الطعام؟",
    faq_nutrition_a4: "نوفر معلومات الحساسية لجميع الوجبات المتاحة. ومع ذلك، يتم إعداد الوجبات في مطابخ تجارية قد تتعامل مع مسببات الحساسية الشائعة. إذا كان لديك حساسية شديدة، يرجى الاتصال بالمنشأة مباشرة قبل الطلب.",
    faq_account_q1: "كيف أعيد تعيين كلمة مروري؟",
    faq_account_a1: "اضغط على 'نسيت كلمة المرور' في صفحة تسجيل الدخول وأدخل عنوان بريدك الإلكتروني. سنرسل لك رابطاً آمناً لإعادة تعيين كلمة المرور. ينتهي صلاحية الرابط بعد 24 ساعة للأمان.",
    faq_account_q2: "كيف يمكنني التواصل مع دعم العملاء؟",
    faq_account_a2: "يمكنك الوصول إلى فريق الدعم لدينا من خلال صفحة الدعم في حسابك، أو بإرسال بريد إلكتروني إلى support@nutribox.com، أو بالاتصال بخط المساعدة الخاص بنا. نستجيب عادة خلال 24 ساعة.",
    faq_account_q3: "هل يمكنني استخدام عناوين توصيل متعددة؟",
    faq_account_a3: "نعم! يمكنك حفظ عناوين متعددة (المنزل، العمل، إلخ) في حسابك واختيار العنوان المناسب عند جدولة كل توصيل وجبة.",
    faq_account_q4: "كيف أُحيل صديقاً؟",
    faq_account_a4: "قم بزيارة برنامج الشراكة في حسابك للحصول على رمز الإحالة الخاص بك. عندما يسجل الأصدقاء باستخدام رمزك ويضعون طلبات،Earn عمولاتك تلقائياً!",
    faq_help_center: "مركز المساعدة",
    faq_frequently_asked: "الأسئلة الشائعة",
    faq_find_answers: "ابحث عن إجابات للأسئلة الشائعة حول نوتريو. هل لا يمكنك العثور على ما تبحث عنه؟",
    faq_contact_us: "اتصل بنا",
    faq_still_questions: "هل لا تزال لديك أسئلة؟",
    faq_support_team: "فريق الدعم لدينا هنا لمساعدتك في أي أسئلة أو مخاوف.",
    faq_contact_support: "التواصل مع الدعم",
    faq_submit_ticket: "إرسال تذكرة",
    back_to_profile: "رجوع للملف الشخصي",

    // Cancellation Flow
    cancel_subscription: "إلغاء الاشتراك",
    step_1_of_4: "الخطوة 1 من 4",
    step_2_of_4: "الخطوة 2 من 4",
    step_3_of_4: "الخطوة 3 من 4",
    step_4_of_4: "الخطوة 4 من 4",
    why_are_you_leaving: "لماذا تغادر؟",
    feedback_helps_improve: "تعليقاتك تساعدنا في تحسين خدمتنا للجميع",
    tell_us_more_optional: "أخبرنا المزيد (اختياري)",
    feedback_placeholder: "تعليقك قيم بالنسبة لنا...",
    before_you_go_options: "قبل أن تغادر، لدينا بعض الخيارات التي قد تساعدك في البقاء على المسار الصحيح لأهدافك الصحية.",
    keep_subscription: "الاحتفاظ بالاشتراك",
    need_a_break: "هل تحتاج إلى استراحة بدلاً من ذلك؟",
    pause_keeps_benefits: "الإيقاف المؤقت يحافظ على مزاياك. مثالي للإجازات أو فترات العمل المزدحم.",
    resume_automatically: "الاستئناف تلقائياً",
    pause_subscription: "إيقاف الاشتراك مؤقتاً",
    no_pause_offers: "لا توجد عروض توقف متاحة",
    what_happens_when_pause: "ماذا يحدث عند الإيقاف المؤقت؟",
    subscription_remains_active: "اشتراكك يظل نشطاً",
    billing_delayed: "الفوترة التالية تتأخر حتى تستأنف",
    meal_credits_safe: "جميع وحدات الوجبات الخاصة بك تبقى آمنة",
    favorite_meals_available: "وجباتك المفضلة لا تزال متاحة",
    continue_to_cancel: "المتابعة إلى الإلغاء",
    how_about_discount: "ماذا عن خصم؟",
    special_discount_for_you: "لقد طبقنا خصماً خاصاً لك فقط. ابقَ ووفّر!",
    save_percent: "وفّر {percent}%",
    you_save_amount: "توفّر {amount}!",
    apply_discount: "تطبيق الخصم",
    no_discount_offers: "لا توجد عروض خصم متاحة",
    limited_time_offer: "عرض لفترة محدودة:",
    discount_only_now: "هذا الخصم متاح الآن فقط. إذا قمت بالإلغاء، لن تتمكن من المطالبة بهذا السعر عند إعادة الاشتراك.",
    final_step_cancel: "الخطوة الأخيرة: إلغاء الاشتراك",
    sorry_to_see_you_go: "نأسف لرحيلك. إليك خياراتك النهائية.",
    consider_downgrade: "فكر في الترقيع بدلاً من ذلك:",
    switch_to_plan: "التبديل إلى خطة {tier}",
    take_bonus_credits: "أو اقبل أرصدة إضافية:",
    accept_bonus: "قبول {amount} ر.ق كرصيد إضافي",
    confirm_cancellation: "تأكيد الإلغاء",
    you_will_lose_access: "ستفقد الوصول إلى:",
    remaining_meals: "وجباتك المتبقية {count} في هذه الدورة",
    all_subscription_benefits: "جميع مزايا الاشتراك",
    discounted_pricing: "أسعار الوجبات المخفضة",
    priority_delivery: "توصيل ذو أولوية",
    access_continues_until: "يستمر وصولك حتى {date}",
    cancelling: "جاري الإلغاء...",

    // Cancellation reasons
    reason_too_expensive: "مكلف جداً",
    reason_too_expensive_desc: "تكاليف الاشتراك مرتفعة جداً لميزانيتي",
    reason_not_using: "لا أستخدمه بما يكفي",
    reason_not_using_desc: "لا أطلب وجبات كافية لتبرير التكلفة",
    reason_moving: "الانتقال",
    reason_moving_desc: "أنا أنتقل ولن أتمكن من استخدام الخدمة",
    reason_dietary: "تغييرات غذائية",
    reason_dietary_desc: "احتياجاتي الغذائية تغيرت ولا تتطابق مع القائمة",
    reason_quality: "مشاكل في الجودة",
    reason_quality_desc: "لست راضياً عن جودة الطعام",
    reason_delivery: "مشاكل في التوصيل",
    reason_delivery_desc: "أواجه مشاكل مع توقيت وموثوقية التوصيل",
    reason_alternative: "وجدت بديلاً",
    reason_alternative_desc: "وجدت خدمة وجبات أخرى تعمل بشكل أفضل",
    reason_temporary: "استراحة مؤقتة",
    reason_temporary_desc: "أحتاج فقط إلى إيقاف مؤقت وأخطط للعودة",
    reason_other: "أخرى",
    reason_other_desc: "شيء آخر غير مدرج هنا",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

// ─── Context ──────────────────────────────────────────────────────────────────
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey | string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => translations.en[key as keyof typeof translations.en] ?? translations.en[key as keyof typeof translations.en] ?? key,
  isRTL: false,
});

// ─── Provider ─────────────────────────────────────────────────────────────────
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      return (localStorage.getItem("nutrio_language") as Language) || "en";
    } catch {
      return "en";
    }
  });

  const isRTL = language === "ar";

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("nutrio_language", lang);
    } catch {}
  };

  // Apply dir and lang attributes to the document root
  useEffect(() => {
    document.documentElement.setAttribute("dir", isRTL ? "rtl" : "ltr");
    document.documentElement.setAttribute("lang", language);
    if (isRTL) {
      document.documentElement.classList.add("rtl");
    } else {
      document.documentElement.classList.remove("rtl");
    }
  }, [language, isRTL]);

  const t = (key: TranslationKey | string): string => {
    return translations[language][key as keyof typeof translations.en] ?? translations.en[key as keyof typeof translations.en] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

// ─── Hook ─────────────────────────────────────────────────────────────────────
export function useLanguage() {
  return useContext(LanguageContext);
}
