-- ============================================================================
-- Fix: PostgREST FK resolution for drivers and delivery_jobs
-- Date: 2026-06-25
-- Problem: PGRST200 errors on AdminDeliveries page
--   - drivers.user_id → auth.users FK not resolved by PostgREST schema cache
--   - delivery_jobs.driver_id → drivers FK not resolved
--   - delivery_jobs.schedule_id → meal_schedules FK not resolved
--   - Missing columns: is_active, phone_number, total_earnings on drivers
-- ============================================================================

-- ============================================================================
-- PART 1: Add missing columns to drivers table
-- ============================================================================

-- is_active: used by getOnlineDrivers() filter (is_active=eq.true)
-- The table has is_online but code queries is_active
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'drivers' AND column_name = 'is_active'
  ) THEN
    ALTER TABLE public.drivers ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT true;
    -- Sync existing data: is_active mirrors is_online
    UPDATE public.drivers SET is_active = is_online;
  END IF;
END$$;

-- phone_number: used by AdminDeliveries OnlineDriver interface
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'drivers' AND column_name = 'phone_number'
  ) THEN
    ALTER TABLE public.drivers ADD COLUMN phone_number TEXT;
  END IF;
END$$;

-- total_earnings: used by AdminDeliveries OnlineDriver interface
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'drivers' AND column_name = 'total_earnings'
  ) THEN
    ALTER TABLE public.drivers ADD COLUMN total_earnings NUMERIC(10,2) DEFAULT 0;
  END IF;
END$$;

-- ============================================================================
-- PART 2: Ensure explicit named FK constraints for PostgREST resolution
-- ============================================================================

-- 2a. drivers.user_id → auth.users(id)
-- The inline FK exists but PostgREST needs a named constraint it can detect.
-- Drop the inline constraint and recreate as named.
DO $$
DECLARE
  v_constraint_name TEXT;
BEGIN
  -- Find the existing FK constraint name (auto-generated by inline REFERENCES)
  SELECT con.conname INTO v_constraint_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  WHERE rel.relname = 'drivers'
    AND con.contype = 'f'
    AND con.confrelid = 'auth.users'::regclass;

  IF v_constraint_name IS NOT NULL AND v_constraint_name != 'fk_drivers_user_id' THEN
    -- Drop the auto-generated constraint
    EXECUTE format('ALTER TABLE public.drivers DROP CONSTRAINT %I', v_constraint_name);
  END IF;

  -- Create named constraint if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_drivers_user_id'
  ) THEN
    ALTER TABLE public.drivers
    ADD CONSTRAINT fk_drivers_user_id
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END$$;

-- 2b. delivery_jobs.driver_id → drivers(id)
DO $$
DECLARE
  v_constraint_name TEXT;
BEGIN
  SELECT con.conname INTO v_constraint_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  WHERE rel.relname = 'delivery_jobs'
    AND con.contype = 'f'
    AND con.confrelid = 'public.drivers'::regclass;

  IF v_constraint_name IS NOT NULL AND v_constraint_name != 'fk_delivery_jobs_driver_id' THEN
    EXECUTE format('ALTER TABLE public.delivery_jobs DROP CONSTRAINT %I', v_constraint_name);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_delivery_jobs_driver_id'
  ) THEN
    ALTER TABLE public.delivery_jobs
    ADD CONSTRAINT fk_delivery_jobs_driver_id
    FOREIGN KEY (driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;
  END IF;
END$$;

-- 2c. delivery_jobs.schedule_id → meal_schedules(id)
DO $$
DECLARE
  v_constraint_name TEXT;
BEGIN
  SELECT con.conname INTO v_constraint_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  WHERE rel.relname = 'delivery_jobs'
    AND con.contype = 'f'
    AND con.confrelid = 'public.meal_schedules'::regclass;

  IF v_constraint_name IS NOT NULL AND v_constraint_name != 'fk_delivery_jobs_schedule_id' THEN
    EXECUTE format('ALTER TABLE public.delivery_jobs DROP CONSTRAINT %I', v_constraint_name);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_delivery_jobs_schedule_id'
  ) THEN
    ALTER TABLE public.delivery_jobs
    ADD CONSTRAINT fk_delivery_jobs_schedule_id
    FOREIGN KEY (schedule_id) REFERENCES public.meal_schedules(id) ON DELETE CASCADE;
  END IF;
END$$;

-- 2d. delivery_jobs → meal_schedules → meals → restaurants chain
-- These should already exist from meal_schedules table definition,
-- but ensure they're named for PostgREST resolution.
DO $$
DECLARE
  v_constraint_name TEXT;
BEGIN
  -- meal_schedules.meal_id → meals(id)
  SELECT con.conname INTO v_constraint_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  WHERE rel.relname = 'meal_schedules'
    AND con.contype = 'f'
    AND con.confrelid = 'public.meals'::regclass;

  IF v_constraint_name IS NOT NULL AND v_constraint_name != 'fk_meal_schedules_meal_id' THEN
    EXECUTE format('ALTER TABLE public.meal_schedules DROP CONSTRAINT %I', v_constraint_name);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_meal_schedules_meal_id'
  ) THEN
    ALTER TABLE public.meal_schedules
    ADD CONSTRAINT fk_meal_schedules_meal_id
    FOREIGN KEY (meal_id) REFERENCES public.meals(id) ON DELETE CASCADE;
  END IF;

  -- meals.restaurant_id → restaurants(id)
  SELECT con.conname INTO v_constraint_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  WHERE rel.relname = 'meals'
    AND con.contype = 'f'
    AND con.confrelid = 'public.restaurants'::regclass;

  IF v_constraint_name IS NOT NULL AND v_constraint_name != 'fk_meals_restaurant_id' THEN
    EXECUTE format('ALTER TABLE public.meals DROP CONSTRAINT %I', v_constraint_name);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_meals_restaurant_id'
  ) THEN
    ALTER TABLE public.meals
    ADD CONSTRAINT fk_meals_restaurant_id
    FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id) ON DELETE CASCADE;
  END IF;
END$$;

-- ============================================================================
-- PART 3: Refresh PostgREST schema cache
-- ============================================================================
-- Notify PostgREST to reload its schema cache
NOTIFY pgrst, 'reload schema';
